add tailwind
singularity-autumn-2023/team4-skilled-elearning-landing-page pull request #1
Opened 2023-12-14 17:29 UTC by nurliyev

Please checkout tailwind, looks like it works correctly

2023-12-16 06:02 UTC, talgat-ruby commented
@IFudor1a @samekeekz please review

2023-12-16 06:05 UTC, talgat-ruby requested changes
все круто, только уберите лишний контент

2023-12-16 06:05 UTC, talgat-ruby commented on index.html
> +    <img
то что сделали просто для теста уберите. Будет просто мешаться.

2023-12-16 08:30 UTC, IFudor1a approved these changes

2023-12-16 21:17 UTC, samekeekz approved these changes
looks good

2023-12-17 07:52 UTC, nurliyev commented on index.html
> +    <img
удалил тестовый код из html

2023-12-17 07:54 UTC, talgat-ruby approved these changes
LGTM!

2023-12-17 07:57 UTC, merged

2023-12-17 15:04 UTC, samekeekz reviewed
ok