full header by Alisher for pr
singularity-autumn-2023/team4-skilled-elearning-landing-page pull request #2
Opened 2023-12-17 10:15 UTC by IFudor1a

Header for desktop, tablet, mobile and configuration of tailwind css (Variables, screens);

2023-12-17 10:31 UTC, talgat-ruby requested changes
все отлично только вопрос зачем настраивать tailwind config?

2023-12-17 10:31 UTC, talgat-ruby commented on tailwind.config.js
> +        },
зачем вы настраиваете все это?

2023-12-17 10:37 UTC, IFudor1a commented on tailwind.config.js
> +        },
для удобство, tailwind сам по себе довольно таки громосткий и можно легко запутаться где что поставил (работа со шрифтам и с градиентом как пример). После конфигурации tailwind с кодом довольно таки легче работать, а также появляется возможность переиспользование имеющихся стилей. Настроил скрины поскольку при работе с tailwind мне не понравились дефолтные media поинты (начал работу с десктопной версии поэтому дефолтные breakpoints мне бы не подошли)

2023-12-17 10:40 UTC, talgat-ruby approved these changes

2023-12-17 13:18 UTC, nurliyev approved these changes

2023-12-17 15:05 UTC, samekeekz approved these changes
gogo

2023-12-18 14:51 UTC, merged

2023-12-18 15:23 UTC, samekeekz reviewed
good